# nixpacks.toml

[phases.setup]
# Installe les dépendances système requises par Playwright pour Chromium
# Basé sur les dépendances typiques et la sortie de `playwright install-deps`
aptPkgs = [
    "libglib2.0-0",
    "libnss3",
    "libnspr4",
    "libdbus-1-3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libgbm1",
    "libasound2",
    "libatspi2.0-0",
    "libxrender1",
    "libxshmfence1",
    "libxrandr2",
    "libxfixes3",
    "libxcursor1",
    "libxdamage1",
    "libxcomposite1",
    "libx11-xcb1",
    "libfontconfig1", 
    "libxss1",      
    "xvfb", 
    "fonts-liberation", 
    "wget",
    "xdg-utils"
]